"""empty message

Revision ID: 1956cad689dc
Revises: 0c79062bd2bf
Create Date: 2020-02-16 21:07:35.712990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1956cad689dc'
down_revision = '0c79062bd2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=120), nullable=False),
    sa.Column('customer', sa.String(length=32), nullable=True),
    sa.Column('level_a', sa.String(length=8), nullable=False),
    sa.Column('number_a', sa.String(length=8), nullable=False),
    sa.Column('description_a', sa.String(length=8), nullable=False),
    sa.Column('rev_a', sa.String(length=8), nullable=False),
    sa.Column('qty_a', sa.String(length=8), nullable=False),
    sa.Column('ref_des_a', sa.String(length=8), nullable=False),
    sa.Column('ref_des_delimiter_a', sa.String(length=8), nullable=False),
    sa.Column('mfg_name_a', sa.String(length=8), nullable=False),
    sa.Column('mfg_number_a', sa.String(length=8), nullable=False),
    sa.Column('level_b', sa.String(length=8), nullable=False),
    sa.Column('number_b', sa.String(length=8), nullable=False),
    sa.Column('description_b', sa.String(length=8), nullable=False),
    sa.Column('rev_b', sa.String(length=8), nullable=False),
    sa.Column('qty_b', sa.String(length=8), nullable=False),
    sa.Column('ref_des_b', sa.String(length=8), nullable=False),
    sa.Column('ref_des_delimiter_b', sa.String(length=8), nullable=False),
    sa.Column('mfg_name_b', sa.String(length=8), nullable=False),
    sa.Column('mfg_number_b', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapping_template')
    # ### end Alembic commands ###
